### ISSUE TITLE
Cant open Jacktor torrents menu, nor use it Jacktook [Kodi Omega]

### ISSUE THREAD

**Issue by Anon1337Elite** [Sam-Max/plugin.video.jacktorr#2] opened 2024-07-11 15:14 UTC
It shows error every time accessing torrents 

log; 

2024-07-11 17:01:08.787 T:5048    error <general>: [plugin.video.jacktorr] Caught exception:
                                                   Traceback (most recent call last):
                                                     File "C:\Library\General\Utilities\Programs\Shoko\Kodi\portable_data\addons\script.module.urllib3\lib\urllib3\connection.py", line 203, in _new_conn
                                                       sock = connection.create_connection(
                                                     File "C:\Library\General\Utilities\Programs\Shoko\Kodi\portable_data\addons\script.module.urllib3\lib\urllib3\util\connection.py", line 85, in create_connection
                                                       raise err
                                                     File "C:\Library\General\Utilities\Programs\Shoko\Kodi\portable_data\addons\script.module.urllib3\lib\urllib3\util\connection.py", line 73, in create_connection
                                                       sock.connect(sa)
                                                   ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it
                                                   
                                                   The above exception was the direct cause of the following exception:
                                                   
                                                   Traceback (most recent call last):
                                                     File "C:\Library\General\Utilities\Programs\Shoko\Kodi\portable_data\addons\script.module.urllib3\lib\urllib3\connectionpool.py", line 790, in urlopen
                                                       response = self._make_request(
                                                     File "C:\Library\General\Utilities\Programs\Shoko\Kodi\portable_data\addons\script.module.urllib3\lib\urllib3\connectionpool.py", line 496, in _make_request
                                                       conn.request(
                                                     File "C:\Library\General\Utilities\Programs\Shoko\Kodi\portable_data\addons\script.module.urllib3\lib\urllib3\connection.py", line 395, in request
                                                       self.endheaders()
                                                     File "C:\Library\General\Utilities\Programs\Shoko\Kodi\system\python\Lib\http\client.py", line 1251, in endheaders
                                                       self._send_output(message_body, encode_chunked=encode_chunked)
                                                     File "C:\Library\General\Utilities\Programs\Shoko\Kodi\system\python\Lib\http\client.py", line 1011, in _send_output
                                                       self.send(msg)
                                                     File "C:\Library\General\Utilities\Programs\Shoko\Kodi\system\python\Lib\http\client.py", line 951, in send
                                                       self.connect()
                                                     File "C:\Library\General\Utilities\Programs\Shoko\Kodi\portable_data\addons\script.module.urllib3\lib\urllib3\connection.py", line 243, in connect
                                                       self.sock = self._new_conn()
                                                     File "C:\Library\General\Utilities\Programs\Shoko\Kodi\portable_data\addons\script.module.urllib3\lib\urllib3\connection.py", line 218, in _new_conn
                                                       raise NewConnectionError(
                                                   urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x000001C755C01670>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it
                                                   
                                                   The above exception was the direct cause of the following exception:
                                                   
                                                   Traceback (most recent call last):
                                                     File "C:\Library\General\Utilities\Programs\Shoko\Kodi\portable_data\addons\script.module.requests\lib\requests\adapters.py", line 486, in send
                                                       resp = conn.urlopen(
                                                     File "C:\Library\General\Utilities\Programs\Shoko\Kodi\portable_data\addons\script.module.urllib3\lib\urllib3\connectionpool.py", line 844, in urlopen
                                                       retries = retries.increment(
                                                     File "C:\Library\General\Utilities\Programs\Shoko\Kodi\portable_data\addons\script.module.urllib3\lib\urllib3\util\retry.py", line 515, in increment
                                                       raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
                                                   urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=5665): Max retries exceeded with url: /torrents (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C755C01670>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "C:\Library\General\Utilities\Programs\Shoko\Kodi\portable_data\addons\plugin.video.jacktorr\lib\torrserver\api.py", line 140, in _request
                                                       return self._session.request(
                                                     File "C:\Library\General\Utilities\Programs\Shoko\Kodi\portable_data\addons\script.module.requests\lib\requests\api.py", line 59, in request
                                                       return session.request(method=method, url=url, **kwargs)
                                                     File "C:\Library\General\Utilities\Programs\Shoko\Kodi\portable_data\addons\script.module.requests\lib\requests\sessions.py", line 589, in request
                                                       resp = self.send(prep, **send_kwargs)
                                                     File "C:\Library\General\Utilities\Programs\Shoko\Kodi\portable_data\addons\script.module.requests\lib\requests\sessions.py", line 703, in send
                                                       r = adapter.send(request, **kwargs)
                                                     File "C:\Library\General\Utilities\Programs\Shoko\Kodi\portable_data\addons\script.module.requests\lib\requests\adapters.py", line 519, in send
                                                       raise ConnectionError(e, request=request)
                                                   requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=5665): Max retries exceeded with url: /torrents (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C755C01670>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "C:\Library\General\Utilities\Programs\Shoko\Kodi\portable_data\addons\plugin.video.jacktorr\lib\navigation.py", line 545, in run
                                                       plugin.run()
                                                     File "C:\Library\General\Utilities\Programs\Shoko\Kodi\portable_data\addons\script.module.routing\lib\routing.py", line 130, in run
                                                       self._dispatch(self.path)
                                                     File "C:\Library\General\Utilities\Programs\Shoko\Kodi\portable_data\addons\script.module.routing\lib\routing.py", line 141, in _dispatch
                                                       view_func(**kwargs)
                                                     File "C:\Library\General\Utilities\Programs\Shoko\Kodi\portable_data\addons\plugin.video.jacktorr\lib\navigation.py", line 86, in wrapper
                                                       ret = func(*args, **kwargs)
                                                     File "C:\Library\General\Utilities\Programs\Shoko\Kodi\portable_data\addons\plugin.video.jacktorr\lib\navigation.py", line 204, in torrents
                                                       for torrent in api.torrents():
                                                     File "C:\Library\General\Utilities\Programs\Shoko\Kodi\portable_data\addons\plugin.video.jacktorr\lib\torrserver\api.py", line 64, in torrents
                                                       return self._post("/torrents", data=dumps({"action": "list"})).json()
                                                     File "C:\Library\General\Utilities\Programs\Shoko\Kodi\portable_data\addons\plugin.video.jacktorr\lib\torrserver\api.py", line 127, in _post
                                                       return self._request("post", url, **kwargs)
                                                     File "C:\Library\General\Utilities\Programs\Shoko\Kodi\portable_data\addons\plugin.video.jacktorr\lib\torrserver\api.py", line 144, in _request
                                                       raise TorrServerError(str(e))
                                                   lib.torrserver.api.TorrServerError: HTTPConnectionPool(host='127.0.0.1', port=5665): Max retries exceeded with url: /torrents (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C755C01670>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))

**Comment by salim-b** [comment] 2024-07-11 15:33
I suspect this is a duplicate of https://github.com/Sam-Max/plugin.video.jacktorr/issues/1.

**Comment by Sam-Max** [comment] 2024-07-11 20:55
Sorry for the delay answer, Jacktorr has not inbuilt daemon to run the TorrServer service, you need to deploy TorrServer server on another pc using docker for example, and configure Jacktorr with that server information.

**Closed as completed** 2024-07-12 01:26 UTC

**Comment by Anon1337Elite** [comment] 2024-07-12 01:38
> Sorry for the delay answer, Jacktorr has not inbuilt daemon to run the TorrServer service, you need to deploy TorrServer server on another pc using docker for example, and configure Jacktorr with that server information.

works thx , maybe u can include it with the addon simmilar to how elementum runs an exe
